### ISSUE TITLE
[crash] Thermoo Patches crashes with Armor Points ++ enabled.

### ISSUE THREAD

**Issue by N0aW** [TheDeathlyCow/thermoo-patches#1]
[Crash Log](https://mclo.gs/B2zcYRC)

Enabled Mods:
- Fabric API
- Thermoo
- Thermoo Patches
- Armor Points ++
- ClothConfig

**Comment by N0aW** [comment]
Nvm it just reguired libhud

**Comment by TheDeathlyCow** [comment]
Wow... cool to see someone already using this even though its not yet published. No worries.
