### ISSUE TITLE
Crash on startup with Immersive Weathering

### ISSUE THREAD

**Issue by TeslaP09** [TheDeathlyCow/thermoo-patches#5]
I first noticed this in my modpack, but isolating the mods gives the same crash: 

[crash-2024-05-04_17.53.21-client.txt](https://github.com/TheDeathlyCow/thermoo-patches/files/15210221/crash-2024-05-04_17.53.21-client.txt)
[latest.log](https://github.com/TheDeathlyCow/thermoo-patches/files/15210222/latest.log)

Mods installed:
Immersive Weathering 2.0.1, Termoo 2.3.1, Scorchful 0.6.2, Frostiful 1.0.9, Thermoo Patches 1.0.0, Moonlight Lib 2.11.14, Cloth Config API 11.1.118, Fabric API 0.92.1, Termoo Patches 1.0.0

I'm not a programmer, but Termoo Patches seems to want to inject something into 'onLandedUpon' in com.ordana.immersive_weathering.blocks.IcicleBlock, which, after quickly CTRL + F'ing that file in Immersive Weathering's source code, does not exist (as stated in the crash report)

**Comment by TheDeathlyCow** [comment]
Hmm seems to be because of a difference in mappings. Immersive Weathering uses mojmap so `onLandedUpon` is actually called `fallOn` in their code. Will have a fix later today.
